Repository GES-compchem/GES-comp-echem, pull requests merged in 2023-02, with the labels that each got.

#84 Bugfixes
  compechem/engines/dftbplus.py
  compechem/engines/orca.py
  compechem/engines/xtb.py
  compechem/tools/internaltools.py
  compechem/tools/vmdtools.py
  tests/integration/test_orca_integration.py
  tests/integration/utils/orca_examples/water_spe_CCSD.inp
  tests/integration/utils/orca_examples/water_spe_CCSD.out
Labels: bug, enhancement

#86 Early implementation of pka calculation with generic engine + first version of the automatic pka calculation tool
  compechem/constants.py
  compechem/engines/orca.py
  compechem/functions/pka.py
  compechem/tools/reorderenergies.py
  tests/functional/test_pka.py
  tests/functional/utils/xyz_files/acetic_acid.xyz
  tests/functional/utils/xyz_files/deprotonated_acetic_acid.xyz
  tox.ini
Labels: enhancement

#88 Added mpi flags options to DFTB+
  compechem/engines/dftbplus.py
  compechem/engines/orca.py
Labels: enhancement

#89 Version bump to 0.3.0
  compechem/config.py
  compechem/core/properties.py
  compechem/engines/dftbplus.py
  compechem/engines/orca.py
  compechem/engines/xtb.py
  compechem/functions/__init__.py
  compechem/functions/pka.py
  compechem/functions/potential.py
  compechem/tools/internaltools.py
  docs/API/functions.md
  docs/Guide/functions.md
  docs/release-notes.md
  docs/user-guide.md
  meta.yaml
  setup.py
  tests/functional/test_pka.py
  tests/functional/test_potential.py
  tests/functional/utils/xyz_files/1,4-dimethoxybenzene.xyz
  tests/functional/utils/xyz_files/2-methoxyphenol_deprot.xyz
  tests/functional/utils/xyz_files/2-methoxyphenol_prot.xyz
  tests/integration/test_level_of_theory.py
  tests/integration/test_orca_integration.py
  tests/integration/test_xtb_integration.py
  tests/unit/test_properties.py
Labels: enhancement

#92 Job failure monitoring
  compechem/engines/dftbplus.py
  compechem/engines/orca.py
  compechem/engines/xtb.py
  tests/integration/test_dftbplus_integration.py
  tests/integration/test_orca_integration.py
  tests/integration/test_xtb_integration.py
  tests/integration/utils/dftbplus_examples/error_input.out
  tests/integration/utils/orca_examples/error_in_input.inp
  tests/integration/utils/orca_examples/error_in_input.out
  tests/integration/utils/orca_examples/error_missing_basis.inp
  tests/integration/utils/orca_examples/error_missing_basis.out
  tests/integration/utils/orca_examples/error_scf_not_converged.inp
  tests/integration/utils/orca_examples/error_scf_not_converged.out
  tests/integration/utils/orca_examples/error_wrong_multiplicity.inp
  tests/integration/utils/orca_examples/error_wrong_multiplicity.out
  tests/integration/utils/xtb_examples/error_in_input.out
  tests/integration/utils/xtb_examples/error_scf_not_converged.out
  tests/integration/utils/xyz_files/cursed_water.xyz
  tests/integration/utils/xyz_files/europium-aquoion.xyz
Labels: enhancement

#94 Bugfix in orca e dftbplus
  compechem/engines/dftbplus.py
  compechem/engines/orca.py
Labels: bug
